import Head from "next/head";
import Work from "../components/work";

export default function WorkPage() {
  filterSelection("all");
  function filterSelection(c) {
    var x, i;
    x = document.getElementsByClassName("filterDiv");
    if (c == "all") c = "";
    // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
    for (i = 0; i < x.length; i++) {
      w3RemoveClass(x[i], "show");
      if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
    }
  }

  // Show filtered elements
  function w3AddClass(element, name) {
    var i, arr1, arr2;
    arr1 = element.className.split(" ");
    arr2 = name.split(" ");
    for (i = 0; i < arr2.length; i++) {
      if (arr1.indexOf(arr2[i]) == -1) {
        element.className += " " + arr2[i];
      }
    }
  }

  // Hide elements that are not selected
  function w3RemoveClass(element, name) {
    var i, arr1, arr2;
    arr1 = element.className.split(" ");
    arr2 = name.split(" ");
    for (i = 0; i < arr2.length; i++) {
      while (arr1.indexOf(arr2[i]) > -1) {
        arr1.splice(arr1.indexOf(arr2[i]), 1);
      }
    }
    element.className = arr1.join(" ");
  }

  // Add active class to the current control button (highlight it)
  var btnContainer = document.getElementById("myBtnContainer");
  var btns = btnContainer.getElementsByClassName("btn");
  for (var i = 0; i < btns.length; i++) {
    btns[i].addEventListener("click", function () {
      var current = document.getElementsByClassName("active");
      current[0].className = current[0].className.replace(" active", "");
      this.className += " active";
    });
  }
  return (
    <div>
      <Head>
        <title>NextJS Work</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="bg-gradient-to-r from-purple-500 to-pink-500 px-6">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-3xl text-center font-bold mb-6 p-4">Work</h1>
          {/* <!-- Control buttons --> */}
          <div id="myBtnContainer">
            <button className="btn active" onclick="filterSelection('all')">
              {" "}
              Show all
            </button>
            <button className="btn" onclick="filterSelection('cars')">
              {" "}
              Cars
            </button>
            <button className="btn" onclick="filterSelection('animals')">
              {" "}
              Animals
            </button>
            <button className="btn" onclick="filterSelection('fruits')">
              {" "}
              Fruits
            </button>
            <button className="btn" onclick="filterSelection('colors')">
              {" "}
              Colors
            </button>
          </div>
          <div className="contain">
            <div className="filterDiv">
              <Work
                workTitle="Sukoon"
                imageUrl="/Sukoon.png"
                tagName="HTML, CSS, JS"
                about="This is a stress-relieving website project made in my first hackathon Hackofiesta. This project is under the theme Healthcare. This project provides one step solution to get relief from your stress. Live a stress-free life.🕊️"
              />
            </div>
            <div className="filterDiv">
              <Work
                workTitle="Moody"
                imageUrl="/Sukoon.png"
                tagName="HTML, Tailwind CSS"
                about="Moody is a Chrome extension that will help you filter your home page of your Chrome Browser according to your mood. It helps you to do your work according to your mood and also get back your mood to normal. 🕊️"
              />
            </div>
            <div className="filterDiv">
              <Work
                workTitle="Sukoon"
                imageUrl="/Sukoon.png"
                tagName="HTML, CSS, JS"
                about="This is a stress-relieving website project made in my first hackathon Hackofiesta. This project is under the theme Healthcare. This project provides one step solution to get relief from your stress. Live a stress-free life.🕊️"
              />
            </div>
            <div className="filterDiv">
              <Work
                workTitle="Sukoon"
                imageUrl="/Sukoon.png"
                tagName="HTML, CSS, JS"
                about="This is a stress-relieving website project made in my first hackathon Hackofiesta. This project is under the theme Healthcare. This project provides one step solution to get relief from your stress. Live a stress-free life.🕊️"
              />
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
